trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'Terraform to azure infrastructure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show

- script: terraform init
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
  displayName: 'Terraform Init'

- script: terraform validate
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
  displayName: 'Terraform Validate'

- script: terraform plan
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
  displayName: 'Terraform Plan'