# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Plan
  displayName: 'Terraform plan stage'

  jobs:
    - job: Terraformplan
      displayName: 'Terraform plan'

      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
          
        - task: TerraformTask@5
          displayName: 'Terraform init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'Azure-terraform to CICD'
            backendAzureRmResourceGroupName: 'RG3-VSCode-Dev'
            backendAzureRmStorageAccountName: 'cicd1storage987'
            backendAzureRmContainerName: 'cicd01container987'
            backendAzureRmKey: 'dev.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            commandOptions: '-out=tfplan'
            environmentServiceNameAzureRM: 'Azure-terraform to CICD'


        
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            Contents: 'tfplan'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/Environment/Dev'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Environment/Dev'
            ArtifactName: 'tfstateplan'
            publishLocation: 'Container'
          
- stage: Apply 
  displayName: 'Terraform Apply Stage'
  dependsOn: Plan

  jobs:
    - deployment: TerraformApply
      displayName: 'Terraform Apply'
      environment: 'Dev'

      strategy: 
        runOnce:
          deploy:
            
            steps:
              
              - checkout: self
              
              - download: current
                artifact: tfstateplan
              
              - script: |
                  echo "System.DefaultWorkingDirectory"
                  echo "Pipeline Workspace"
                  find $(Pipeline.Workspace) -type f
                  displayName: 'Show downloaded files'
                # displayName: 'Check downloaded files'

              - task: TerraformInstaller@1
                displayName: 'Terraform install'
                inputs:
                  terraformVersion: 'latest'

              - task: TerraformTask@5
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
                  backendServiceArm: 'Azure-terraform to CICD'
                  backendAzureRmResourceGroupName: 'RG3-VSCode-Dev'
                  backendAzureRmStorageAccountName: 'cicd1storage987'
                  backendAzureRmContainerName: 'cicd01container987'
                  backendAzureRmKey: 'dev.tfstate'
              
              - task: TerraformTask@5
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
                  commandOptions: 'tfstateplan'
                  environmentServiceNameAzureRM: 'Azure-terraform to CICD'

