# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: plan
    displayName: 'Terraform Plan stage'

    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'

        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
              backendServiceArm: 'Azure-terraform to CICD'
              backendAzureRmResourceGroupName: 'RG3-VSCode-Dev'
              backendAzureRmStorageAccountName: 'cicd1storage987'
              backendAzureRmContainerName: 'cicd01container987'
              backendAzureRmKey: 'dev.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
              environmentServiceNameAzureRM: 'Azure-terraform to CICD'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/Environment/Dev'
              Contents: 'terraformplan'
              TargetFolder: '$(build.artifactstagingdirectory)/Environment/Dev'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'terraformArtifactPlan'
              publishLocation: 'Container'

  - stage: Apply
    displayName: 'Terraform Apply Stage'
    
    jobs:
      - deployment: TerraformApply
        displayName: 'Terraform Apply stage'
        environment: dev

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - download: current
                  artifact: terraformArtifactPlan

                  