trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    backendServiceArm: 'Azure-terraform to CICD'
    backendAzureRmResourceGroupName: 'RG3-VSCode-Dev'
    backendAzureRmStorageAccountName: 'cicd1storage987'
    backendAzureRmContainerName: 'cicd01container987'
    backendAzureRmKey: 'dev.tfstate'

- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'

- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'Azure-terraform to CICD'

- task: PublishBuildArtifacts@1
  displayName: Terraform build Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Environment/Dev'
    ArtifactName: 'terraform-plan'
    publishLocation: 'Container'

