trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- task: AzureCLI@2
  displayName: 'Terraform Workflow'
  inputs:
    azureSubscription: 'Terraform to azure infrastructure'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    inlineScript: |
      az account show
      terraform init
      terraform validate
      terraform plan